version: "1.0"
devices:
    - id: device-001
      name: Demo
      protocol: opcua
      enabled: true
      uns_prefix: plant1/area1/line2
      poll_interval: 10s
      connection:
        host: nexus-opcua-sim
        port: 4840
        timeout: 5s
        retry_count: 3
        retry_delay: 100ms
        slave_id: 1
        opc_endpoint_url: opc.tcp://nexus-opcua-sim:4840
        opc_security_policy: None
        opc_security_mode: ""
        opc_auth_mode: ""
        opc_username: ""
        opc_password: ""
        opc_cert_file: ""
        opc_key_file: ""
        opc_server_cert_file: ""
        opc_insecure_skip_verify: false
        opc_auto_select_endpoint: false
        opc_application_name: ""
        opc_application_uri: ""
        opc_use_subscriptions: false
        opc_publish_interval: ""
        opc_sampling_interval: ""
        s7_rack: 0
        s7_slot: 0
      tags:
        - id: tag-1771836635977
          name: Switch
          data_type: bool
          scale_factor: 1
          topic_suffix: Switch
          enabled: true
          access_mode: readwrite
          register_type: holding_register
          byte_order: big_endian
          register_count: 1
          opc_node_id: ns=2;s=Demo.Switch
        - id: tag-1771861039471
          name: Temperature
          data_type: float64
          scale_factor: 1
          topic_suffix: Temperature
          enabled: true
          access_mode: read
          register_type: holding_register
          byte_order: big_endian
          register_count: 1
          opc_node_id: ns=2;s=Demo.Temperature
